### ISSUE TITLE
Do we need to update the Dockerfile if we want to deploy pack for 3.2dev?

### ISSUE THREAD

**Issue by wantdrink** [StackStorm/st2packs-dockerfiles#15]
Hi there,

The Dockerfile of st2packs-builder specify image as 

`FROM stackstorm/st2:3.0dev
`

If I want to compose packs for 3.2dev do I need to update it to below version?

`FROM stackstorm/st2:3.2dev
`

Thanks.

**Comment by armab** [comment]
You should be fine with the current `st2:3.0dev` because all we need is `st2-pack-install` command from that environment.

**Comment by wantdrink** [comment]
Thanks a lot @armab
