### ISSUE TITLE
How to install packs behind proxy while building st2packs image

### ISSUE THREAD

**Issue by wantdrink** [StackStorm/st2packs-dockerfiles#16]
Hi there,

I've tested installing packs behind a proxy in a ss installed on RHEL and it works well.
But in ss-ha how to install packs with proxy and build image?

E.G. to build image with internet access to install azure is easy:
```
git clone git@github.com:stackstorm/st2packs-dockerfiles
cd st2packs-dockerfiles
docker build --build-arg PACKS="azure" -t myregistry.com/st2packs:1.0 st2packs-image
```

However we cannot change `/etc/default/st2actionrunner` and `/etc/default/st2api `as [installing-packs-from-behind-a-proxy](https://docs.stackstorm.com/packs.html#installing-packs-from-behind-a-proxy) described in the image.

**Comment by armab** [comment]
Try to provide `http_proxy`, `https_proxy` and `no_proxy` as ENV variables in Dockerfile.

A quick example to gen an idea:

```Dockerfile
# Define a list of custom st2 packs to build
ARG PACKS="azure"

FROM stackstorm/st2packs:builder AS builder

# Proxy settings for pack install
ENV http_proxy http://proxy-host/
ENV https_proxy https://proxy-host/
ENV no_proxy 127.0.0.1,localhost

# Install custom st2 packs
RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}
FROM stackstorm/st2packs:runtime

**Comment by armab** [comment]
In fact, take a look at official Docker documentation:
https://docs.docker.com/network/proxy/#set-the-environment-variables-manually

That should be better.

**Comment by wantdrink** [comment]
Thanks @armab , it really helps.
