### ISSUE TITLE
python3 virtualenv for st2 pack

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/st2packs-dockerfiles#18]
Hi, 

I've packs running on standalone stackstrom which I install using command 

`st2 pack install <pack>  --python3`

But as per the doc there is nothing to use python3, I'm on Centos7 and installed both python2 & 3 but by default it's using python2.

`RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}`

I tried changing this command but it didn't work. Is there any way I can run my custom pack with python3.

Any help would be appreciated, thanks in advance!

**Comment by hlxwell** [comment]
same question here.

**Comment by hlxwell** [comment]
solved.

in st2packs-image/Dockerfile add below line


```
FROM stackstorm/st2packs:builder AS builder

# ADD THIS LINE
RUN apt-get install build-essential autoconf libkrb5-dev -y

# Install custom packs
RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}

###########################
# Minimize the image size. Start with alpine:3.8,
# and add only packs and virtualenvs from builder.
FROM stackstorm/st2packs:runtime
```

**Comment by armab** [comment]
https://hub.docker.com/r/stackstorm/st2packs now relies on latest `Python 3` Docker images based on `Ubuntu Bionic` and st2 `v3.3dev`.
